/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.gmousset.arch.vertx.t01

import com.github.gmousset.arch.vertx.t01.http01.HttpApi01Verticle
import io.vertx.core.Vertx
import org.slf4j.LoggerFactory

fun main() {
    val logger = LoggerFactory.getLogger("Main")
    val vertx = Vertx.vertx()
    vertx.deployVerticle(HttpApi01Verticle()).onSuccess { logger.info("Verticles deployed") }
}
